---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thewbillboard/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
